server:
  port: ${APP_PORT:5000}
  address: ${APP_HOST:localhost}
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:rps;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
    username: sa
    password: sa

  jpa:
    hibernate.ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: rps
        jdbc:
          lob.non_contextual_creation: true

  flyway:
    baseline-on-migrate: true
    schemas: rps

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
